name = "indexforpixeldrain"
compatibility_date = "2024-03-14"
pages_build_output_dir = ".next"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install && npm run build"
cwd = "."
watch_dir = "app"

[site]
bucket = ".next"

[env.production]
vars = { NODE_ENV = "production" } 