[build]
command = "npm install && npm run build"
output_directory = ".next"

[build.environment]
NODE_VERSION = "18"
NEXT_PUBLIC_API_URL = "https://pixeldrain.com/api"

[site]
bucket = ".next"

[env.production]
vars = { NODE_ENV = "production" } 