name: Deploy Next.js site to GitHub Pages

on:
  # Executa na push para a branch principal
  push:
    branches: ["main"]
  # Permite executar manualmente a partir da aba Actions
  workflow_dispatch:

# Define permissões do token GITHUB_TOKEN para permitir deployment para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deployment concorrente, pulando execuções em andamento
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: /indexforpixeldrain
      NEXT_PUBLIC_API_URL: https://pixeldrain.com/api
      NODE_OPTIONS: --trace-warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # Gera saída estática em vez de resposta do servidor
          static_site_generator: next
          # Habilitar GitHub Pages se não estiver habilitado
          enablement: true
      - name: List directory structure
        run: |
          find . -type d | sort
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          # Gere uma nova chave de cache quando o lockfile muda
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: |
          npm ci
      - name: Verify setup
        run: |
          node -v
          npm -v
          cat next.config.js
          echo "Variáveis de ambiente configuradas:"
          echo "NEXT_PUBLIC_BASE_PATH: $NEXT_PUBLIC_BASE_PATH"
          echo "NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL"
      - name: Build with Next.js
        run: |
          # Primeiro, remova temporariamente as pastas de API
          mv app/api app/api_backup || true
          # Executar o build com verbosidade máxima
          npm run build --verbose
          # Restaurar a pasta API
          mv app/api_backup app/api || true
          mkdir -p out
          touch out/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Job de deployment
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 